version: 2.1
orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.2

workflows:
  sample:
    jobs:
      - node/test
      - heroku/deploy-via-git:
          force: true # this parameter instructs the push to use a force flag when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git
          requires:
            - node/test
          filters:
            branches:
              only: master 
